server:
  port: 8080

spring:
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1200000
      keepalive-time: 30000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      leak-detection-threshold: 120000
    url: jdbc:mysql://localhost:3306/inventory_system?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&connectTimeout=60000&socketTimeout=300000
    username: root
    password: root0811
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:org/sourcecode/server/mapper/**/*.xml
  type-aliases-package: org.sourcecode.server.**.entity
  mapper-package: org.sourcecode.server.**.mapper
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logger:
  record:
    useEqualsMethod: java.time.LocalDate,java.time.Instant